# -----------------------------------------------------------------------------
# THIS FILE WAS AUTO-GENERATED.
# DO NOT EDIT MANUALLY.
# Generated by: tools/generator_hs_type.py
# -----------------------------------------------------------------------------

import difflib
from dataclasses import dataclass
from enum import Enum


@dataclass
class HSValue():
    """ Internal value type to help with 'HSType'. """
    category: int
    category_value: int
    csv_value: int


class HSIncrementer():
    """ Internal incrementer to help with 'HSType'. """

    def __init__(self):
        self._arr = [0] * 3

    def skill(self) -> HSValue:
        cat_val, csv_val = self._arr[0], self._arr[2]
        self._arr[0] += 1
        self._arr[2] += 1
        return HSValue(category=0, category_value=cat_val, csv_value=csv_val)

    def activity(self, has_csv_mapping=True) -> HSValue:
        cat_val, csv_val = self._arr[1], self._arr[2]
        self._arr[1] += 1

        if not has_csv_mapping:
            csv_val = -1
        else:
            self._arr[2] += 1

        return HSValue(category=1, category_value=cat_val, csv_value=csv_val)


HSCategoryMapperIncrementer = HSIncrementer()

# hs categories are split into 2: skills and misc/activities
# i split it more than that to more accuratly reflect what they are
# or so they're grouped more logically


class HSType(Enum):
    """ 
    Enum of OSRS hiscore categories, each value contains data to make hiscore lookup easier.
    """
    # skills
    overall = HSCategoryMapperIncrementer.skill()
    attack = HSCategoryMapperIncrementer.skill()
    att = attack
    atk = attack
    defence = HSCategoryMapperIncrementer.skill()
    defe = defence
    strength = HSCategoryMapperIncrementer.skill()
    stre = strength
    hitpoints = HSCategoryMapperIncrementer.skill()
    hp = hitpoints
    ranged = HSCategoryMapperIncrementer.skill()
    range = ranged
    prayer = HSCategoryMapperIncrementer.skill()
    pray = prayer
    magic = HSCategoryMapperIncrementer.skill()
    mage = magic
    cooking = HSCategoryMapperIncrementer.skill()
    cook = cooking
    woodcutting = HSCategoryMapperIncrementer.skill()
    wc = woodcutting
    fletching = HSCategoryMapperIncrementer.skill()
    fletch = fletching
    fishing = HSCategoryMapperIncrementer.skill()
    fish = fishing
    firemaking = HSCategoryMapperIncrementer.skill()
    fm = firemaking
    fire = firemaking
    crafting = HSCategoryMapperIncrementer.skill()
    craft = crafting
    smithing = HSCategoryMapperIncrementer.skill()
    smith = smithing
    mining = HSCategoryMapperIncrementer.skill()
    mine = mining
    herblore = HSCategoryMapperIncrementer.skill()
    herb = herblore
    agility = HSCategoryMapperIncrementer.skill()
    agil = agility
    thieving = HSCategoryMapperIncrementer.skill()
    thiev = thieving
    slayer = HSCategoryMapperIncrementer.skill()
    slay = slayer
    farming = HSCategoryMapperIncrementer.skill()
    farm = farming
    runecrafting = HSCategoryMapperIncrementer.skill()
    rc = runecrafting
    rune = runecrafting
    hunter = HSCategoryMapperIncrementer.skill()
    hunt = hunter
    construction = HSCategoryMapperIncrementer.skill()
    con = construction
    sailing = HSCategoryMapperIncrementer.skill()
    sail = sailing

    # activities
    grid_points = HSCategoryMapperIncrementer.activity()
    league_points = HSCategoryMapperIncrementer.activity()
    leagues = league_points
    deadman_points = HSCategoryMapperIncrementer.activity()
    dmm = deadman_points
    bh_hunter = HSCategoryMapperIncrementer.activity()
    bh_rogue = HSCategoryMapperIncrementer.activity()
    bh_legacy_hunter = HSCategoryMapperIncrementer.activity()
    bhl_hunter = bh_legacy_hunter
    bh_legacy_rogue = HSCategoryMapperIncrementer.activity()
    bhl_rogue = bh_legacy_rogue
    clue_all = HSCategoryMapperIncrementer.activity()
    cs_all = clue_all
    clue_beginner = HSCategoryMapperIncrementer.activity()
    cs_beginner = clue_beginner
    clue_easy = HSCategoryMapperIncrementer.activity()
    cs_easy = clue_easy
    clue_medium = HSCategoryMapperIncrementer.activity()
    cs_medium = clue_medium
    clue_hard = HSCategoryMapperIncrementer.activity()
    cs_hard = clue_hard
    clue_elite = HSCategoryMapperIncrementer.activity()
    cs_elite = clue_elite
    clue_master = HSCategoryMapperIncrementer.activity()
    cs_master = clue_master
    lms_rank = HSCategoryMapperIncrementer.activity()
    pvp_arena_rank = HSCategoryMapperIncrementer.activity()
    soulwars_zeal = HSCategoryMapperIncrementer.activity()
    sw_zeal = soulwars_zeal
    rifts_closed = HSCategoryMapperIncrementer.activity()
    colosseum_glory = HSCategoryMapperIncrementer.activity()
    glory = colosseum_glory
    collections_logged = HSCategoryMapperIncrementer.activity()
    clog = collections_logged
    abyssal_sire = HSCategoryMapperIncrementer.activity()
    sire = abyssal_sire
    alchemical_hydra = HSCategoryMapperIncrementer.activity()
    hydra = alchemical_hydra
    amoxliatl = HSCategoryMapperIncrementer.activity()
    amox = amoxliatl
    araxxor = HSCategoryMapperIncrementer.activity()
    artio = HSCategoryMapperIncrementer.activity()
    barrows_chests = HSCategoryMapperIncrementer.activity()
    barrows = barrows_chests
    brutus = HSCategoryMapperIncrementer.activity()
    bryophyta = HSCategoryMapperIncrementer.activity()
    bryo = bryophyta
    callisto = HSCategoryMapperIncrementer.activity()
    calvarion = HSCategoryMapperIncrementer.activity()
    calv = calvarion
    cerberus = HSCategoryMapperIncrementer.activity()
    cerb = cerberus
    chambers_of_xeric = HSCategoryMapperIncrementer.activity()
    cox = chambers_of_xeric
    chambers_of_xeric_challenge_mode = HSCategoryMapperIncrementer.activity()
    raids1 = chambers_of_xeric_challenge_mode
    cox_cm = chambers_of_xeric_challenge_mode
    chaos_elemental = HSCategoryMapperIncrementer.activity()
    chaos_ele = chaos_elemental
    chaos_fanatic = HSCategoryMapperIncrementer.activity()
    chaos_fan = chaos_fanatic
    commander_zilyana = HSCategoryMapperIncrementer.activity()
    zily = commander_zilyana
    saradomin = commander_zilyana
    sara = commander_zilyana
    corporeal_beast = HSCategoryMapperIncrementer.activity()
    corp = corporeal_beast
    crazy_archaeologist = HSCategoryMapperIncrementer.activity()
    crazy_arch = crazy_archaeologist
    dagannoth_prime = HSCategoryMapperIncrementer.activity()
    prime = dagannoth_prime
    dagannoth_rex = HSCategoryMapperIncrementer.activity()
    rex = dagannoth_rex
    dagannoth_supreme = HSCategoryMapperIncrementer.activity()
    supreme = dagannoth_supreme
    deranged_archaeologist = HSCategoryMapperIncrementer.activity()
    deranged_arch = deranged_archaeologist
    doom_of_mokhaiotl = HSCategoryMapperIncrementer.activity()
    doom = doom_of_mokhaiotl
    duke_sucellus = HSCategoryMapperIncrementer.activity()
    duke = duke_sucellus
    general_graardor = HSCategoryMapperIncrementer.activity()
    graardor = general_graardor
    bandos = general_graardor
    giant_mole = HSCategoryMapperIncrementer.activity()
    mole = giant_mole
    grotesque_guardians = HSCategoryMapperIncrementer.activity()
    ggs = grotesque_guardians
    dusk = grotesque_guardians
    hespori = HSCategoryMapperIncrementer.activity()
    kalphite_queen = HSCategoryMapperIncrementer.activity()
    kq = kalphite_queen
    king_black_dragon = HSCategoryMapperIncrementer.activity()
    kbd = king_black_dragon
    kraken = HSCategoryMapperIncrementer.activity()
    kree_arra = HSCategoryMapperIncrementer.activity()
    kree = kree_arra
    armadyl = kree_arra
    arma = kree_arra
    kril_tsutsaroth = HSCategoryMapperIncrementer.activity()
    kril = kril_tsutsaroth
    zamorak = kril_tsutsaroth
    zammy = kril_tsutsaroth
    lunar_chests = HSCategoryMapperIncrementer.activity()
    moons = lunar_chests
    mimic = HSCategoryMapperIncrementer.activity()
    nex = HSCategoryMapperIncrementer.activity()
    nightmare = HSCategoryMapperIncrementer.activity()
    nm = nightmare
    phosanis_nightmare = HSCategoryMapperIncrementer.activity()
    psn = phosanis_nightmare
    phosani = phosanis_nightmare
    obor = HSCategoryMapperIncrementer.activity()
    phantom_muspah = HSCategoryMapperIncrementer.activity()
    pm = phantom_muspah
    muspah = phantom_muspah
    grumbler = phantom_muspah
    sarachnis = HSCategoryMapperIncrementer.activity()
    scorpia = HSCategoryMapperIncrementer.activity()
    scurrius = HSCategoryMapperIncrementer.activity()
    shellbane_gryphon = HSCategoryMapperIncrementer.activity()
    gryphon = shellbane_gryphon
    skotizo = HSCategoryMapperIncrementer.activity()
    sol_heredit = HSCategoryMapperIncrementer.activity()
    sol = sol_heredit
    spindel = HSCategoryMapperIncrementer.activity()
    tempoross = HSCategoryMapperIncrementer.activity()
    fishtodt = tempoross
    the_gauntlet = HSCategoryMapperIncrementer.activity()
    gauntlet = the_gauntlet
    gaunt = the_gauntlet
    the_corrupted_gauntlet = HSCategoryMapperIncrementer.activity()
    cg = the_corrupted_gauntlet
    the_hueycoatl = HSCategoryMapperIncrementer.activity()
    hueycoatl = the_hueycoatl
    huey = the_hueycoatl
    the_leviathan = HSCategoryMapperIncrementer.activity()
    leviathan = the_leviathan
    levi = the_leviathan
    the_royal_titans = HSCategoryMapperIncrementer.activity()
    royal_titans = the_royal_titans
    titans = the_royal_titans
    the_whisperer = HSCategoryMapperIncrementer.activity()
    whisperer = the_whisperer
    whisp = the_whisperer
    theatre_of_blood = HSCategoryMapperIncrementer.activity()
    raids2 = theatre_of_blood
    tob = theatre_of_blood
    theatre_of_blood_hard_mode = HSCategoryMapperIncrementer.activity()
    hmt = theatre_of_blood_hard_mode
    thermonuclear_smoke_devil = HSCategoryMapperIncrementer.activity()
    thermy = thermonuclear_smoke_devil
    tombs_of_amascut = HSCategoryMapperIncrementer.activity()
    raids3 = tombs_of_amascut
    toa = tombs_of_amascut
    tombs_of_amascut_expert_mode = HSCategoryMapperIncrementer.activity()
    toa_expert = tombs_of_amascut_expert_mode
    tzkal_zuk = HSCategoryMapperIncrementer.activity()
    zuk = tzkal_zuk
    inferno = tzkal_zuk
    tztok_jad = HSCategoryMapperIncrementer.activity()
    jad = tztok_jad
    fc = tztok_jad
    vardorvis = HSCategoryMapperIncrementer.activity()
    vard = vardorvis
    venenatis = HSCategoryMapperIncrementer.activity()
    vene = venenatis
    vetion = HSCategoryMapperIncrementer.activity()
    vorkath = HSCategoryMapperIncrementer.activity()
    vork = vorkath
    wintertodt = HSCategoryMapperIncrementer.activity()
    wt = wintertodt
    yama = HSCategoryMapperIncrementer.activity()
    zalcano = HSCategoryMapperIncrementer.activity()
    zalc = zalcano
    zulrah = HSCategoryMapperIncrementer.activity()

    combat = HSValue(-1, -1, -1)

    def get_category(self) -> int:
        """ OSRS hiscore category type. """
        return self.value.category

    def get_category_value(self) -> int:
        """ OSRS hiscore category type value. """
        return self.value.category_value

    def get_csv_value(self) -> int:
        """ OSRS hiscore csv value. """
        return self.value.csv_value

    def is_skill(self) -> bool:
        """ Determine whether the OSRS category represents a skill. """
        return self.get_category() == 0

    def is_activity(self) -> bool:
        """ Determine whether the OSRS category represents an activity, basically every non skill. """
        return self.get_category() == 1

    def is_seasonal_mode(self) -> bool:
        """ Determine whether the OSRS category represents a seasonal gamemode """
        return self in (HSType.league_points, HSType.grid_points, HSType.deadman_points)

    def is_clue(self) -> bool:
        """ Determine whether the OSRS category represents a seasonal gamemode """
        return HSType.clue_all.value.csv_value <= self.value.csv_value <= HSType.clue_master.value.csv_value

    def is_minigame(self) -> bool:
        """ Determine whether the OSRS category represents a mini game """
        return self in (
            HSType.bh_hunter,
            HSType.bh_rogue,
            HSType.bh_legacy_hunter,
            HSType.bh_legacy_rogue,
            HSType.lms_rank,
            HSType.pvp_arena_rank,
            HSType.sw_zeal,
            HSType.rifts_closed,
        )

    def is_misc(self) -> bool:
        """ Misc is really just activities that don't really have a group """
        return self.is_activity() and not (
            self.is_skill()
            or self.is_seasonal_mode()
            or self.is_clue()
            or self.is_minigame()
            or self.is_boss()
            or self.is_combat()
        )

    def is_boss(self) -> bool:
        """ Determine whether the OSRS category represents a boss. """
        return HSType.abyssal_sire.value.csv_value <= self.value.csv_value <= HSType.zulrah.value.csv_value

    def is_combat(self) -> bool:
        """ Determine whether the OSRS category represents a combat stat. """
        return self in {
            HSType.attack, HSType.defence, HSType.strength, HSType.hitpoints,
            HSType.ranged, HSType.prayer, HSType.magic, HSType.combat
        }

    def __str__(self) -> str:
        return self.name

    @staticmethod
    def csv_len() -> int:
        return len([item for item in list(HSType) if item.get_csv_value() != -1])

    @staticmethod
    def get_csv_types() -> list['HSType']:
        return [item for item in list(HSType) if item.get_csv_value() != -1]

    @staticmethod
    def debug() -> list[str]:
        return [f'{v}: {(v.get_category(), v.get_category_value(), v.get_csv_value())}' for v in HSType]

    @staticmethod
    def from_string(s: str) -> 'HSType':
        try:
            return HSType[s.lower()]

        except KeyError:
            grouped = {
                member: tuple(
                    n for n, m in HSType.__members__.items()
                    if m is member
                )
                for member in set(HSType)
            }

            matches = [
                ' | '.join(grouped[HSType.__members__[name]])
                for name in difflib.get_close_matches(
                    s.lower(),
                    HSType.__members__,
                    n=5,
                    cutoff=0.5,
                )
            ]
            matches = list(dict.fromkeys(matches))

            body = (
                ["Closest matches:", *(f"  - {m}" for m in matches)]
                if matches else
                [
                    "Valid values:",
                    *(f"  - {' | '.join(v)}" for v in grouped.values()),
                ]
            )

            raise ValueError('\n'.join([
                f"Unknown HSType: {s!r}",
                "",
                *body,
            ]))


def _bucket_builder():
    return {
        hs.name: (
            'skills' if hs.is_skill()
            else 'seasonal_modes' if hs.is_seasonal_mode()
            else 'clues' if hs.is_clue()
            else 'minigames' if hs.is_minigame()
            else 'bosses' if hs.is_boss()
            else 'misc'
        )
        for hs in HSType
    }


HS_TYPE_BUCKET_MAP = _bucket_builder()
